/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CONTROLADOR.ControladorPrograma;

/**
 *
 * @author roberacc
 */
public class PanelPrograma extends javax.swing.JPanel {

    ControladorPrograma program= new ControladorPrograma();
    /**
     * Creates new form PanelPrograma
     */
    public PanelPrograma() {
        initComponents();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextNivel = new javax.swing.JTextField();
        jTextCreditos = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("GESTION DE PROGRAMAS");
        add(jLabel1);
        jLabel1.setBounds(120, 20, 230, 21);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Codigo");
        add(jLabel2);
        jLabel2.setBounds(40, 90, 70, 18);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Nombre");
        add(jLabel3);
        jLabel3.setBounds(40, 130, 56, 18);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Nivel");
        add(jLabel4);
        jLabel4.setBounds(40, 170, 50, 18);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Creditos");
        add(jLabel5);
        jLabel5.setBounds(40, 210, 80, 18);
        add(jTextCodigo);
        jTextCodigo.setBounds(140, 80, 90, 28);
        add(jTextNombre);
        jTextNombre.setBounds(140, 120, 120, 28);
        add(jTextNivel);
        jTextNivel.setBounds(140, 160, 90, 28);
        add(jTextCreditos);
        jTextCreditos.setBounds(140, 200, 90, 28);

        jButtonRegistrar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonRegistrar.setText("GUARDAR");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        add(jButtonRegistrar);
        jButtonRegistrar.setBounds(30, 260, 90, 30);

        jButtonLimpiar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.setMaximumSize(new java.awt.Dimension(87, 30));
        jButtonLimpiar.setMinimumSize(new java.awt.Dimension(87, 30));
        jButtonLimpiar.setPreferredSize(new java.awt.Dimension(87, 30));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        add(jButtonLimpiar);
        jButtonLimpiar.setBounds(290, 260, 90, 30);

        jButtonEditar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonEditar.setText("EDITAR");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        add(jButtonEditar);
        jButtonEditar.setBounds(160, 260, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        
        program.registrarPrograma(jTextCodigo.getText(),
                jTextNombre.getText(),
                jTextNivel.getText(),
                jTextCreditos.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        limpiarCampos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    
    public void limpiarCampos(){
        
        jTextCodigo.setText("");
        jTextNombre.setText("");
        jTextNivel.setText("");
        jTextCreditos.setText("");
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextCreditos;
    private javax.swing.JTextField jTextNivel;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
